language: php

sudo: false

matrix:
    include:
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true

script:
    - ./bin/lint src
    - ./bin/stupidFunctionalTest.php $token $guild_id $channel_id
